version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    container_name: readnshare-mariadb
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: mydb
      MARIADB_USER: root
      MARIADB_PASSWORD: root
    volumes:
      - mariadb-data:/var/lib/mysql

  redis:
    image: redis:latest
    container_name: readnshare-redis
    ports:
      - "6379:6379"

volumes:
  mariadb-data: